spring:
  jpa:
    hiberante:
      ddl-auto: update
      show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://54.169.143.126:3306/mysql?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: sandy
    password: 256131719xsl
